#include "target.h"

REGISTER_ENTITY(CTarget);

NETVAR_TABLE_BEGIN(CTarget);
NETVAR_TABLE_END();

SAVEDATA_TABLE_BEGIN_EDITOR(CTarget);
SAVEDATA_TABLE_END();

INPUTS_TABLE_BEGIN(CTarget);
INPUTS_TABLE_END();
